/**
 * Règles configurables par défaut de la plateforme
 * Ces règles sont définies dans le code et initialisées automatiquement en base
 */

export interface DefaultRule {
  key: string;
  label: string;
  description?: string;
  category: string;
  valueType: "number" | "boolean" | "string" | "select";
  defaultValue: any;
  currentValue?: any; // Si non défini, utilise defaultValue
  proposalType: "editorial_rules" | "product_evolution" | "ethical_charter" | "other";
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  options?: Array<{ label: string; value: any }>;
}

/**
 * Toutes les règles configurables par défaut de la plateforme
 */
export const DEFAULT_RULES: DefaultRule[] = [
  // ============================================
  // RÈGLES ÉDITORIALES
  // ============================================
  {
    key: "scientific_articles_min_sources",
    label: "Nombre minimum de sources pour articles scientifiques",
    description: "Nombre minimum de sources requises pour valider un article scientifique",
    category: "editorial",
    valueType: "number",
    defaultValue: 3,
    proposalType: "editorial_rules",
    min: 1,
    max: 20,
    step: 1,
    unit: "sources",
  },
  {
    key: "expert_articles_min_sources",
    label: "Nombre minimum de sources pour articles d'experts",
    description: "Nombre minimum de sources requises pour valider un article d'expert",
    category: "editorial",
    valueType: "number",
    defaultValue: 2,
    proposalType: "editorial_rules",
    min: 1,
    max: 15,
    step: 1,
    unit: "sources",
  },
  {
    key: "opinion_articles_min_sources",
    label: "Nombre minimum de sources pour articles d'opinion",
    description: "Nombre minimum de sources requises pour valider un article d'opinion",
    category: "editorial",
    valueType: "number",
    defaultValue: 1,
    proposalType: "editorial_rules",
    min: 0,
    max: 10,
    step: 1,
    unit: "sources",
  },
  {
    key: "min_claims_for_verification",
    label: "Nombre minimum de claims pour vérification",
    description: "Nombre minimum de claims nécessaires pour déclencher une vérification communautaire",
    category: "editorial",
    valueType: "number",
    defaultValue: 3,
    proposalType: "editorial_rules",
    min: 1,
    max: 10,
    step: 1,
    unit: "claims",
  },
  {
    key: "min_expert_reviews",
    label: "Nombre minimum de vérifications expertes",
    description: "Nombre minimum de vérifications par des experts pour valider un article",
    category: "editorial",
    valueType: "number",
    defaultValue: 2,
    proposalType: "editorial_rules",
    min: 1,
    max: 5,
    step: 1,
    unit: "vérifications",
  },
  {
    key: "min_community_verification_score",
    label: "Score minimum de vérification communautaire",
    description: "Score minimum (0-100) requis pour considérer un article comme vérifié par la communauté",
    category: "editorial",
    valueType: "number",
    defaultValue: 70,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
  },
  {
    key: "require_thesis_for_publication",
    label: "Thèse obligatoire pour publication",
    description: "Les articles doivent-ils obligatoirement contenir une thèse pour être publiés ?",
    category: "editorial",
    valueType: "boolean",
    defaultValue: true,
    proposalType: "editorial_rules",
  },
  {
    key: "require_counter_arguments",
    label: "Contre-arguments obligatoires",
    description: "Les articles doivent-ils obligatoirement contenir des contre-arguments pour être publiés ?",
    category: "editorial",
    valueType: "boolean",
    defaultValue: true,
    proposalType: "editorial_rules",
  },
  {
    key: "require_conclusion",
    label: "Conclusion obligatoire",
    description: "Les articles doivent-ils obligatoirement contenir une conclusion pour être publiés ?",
    category: "editorial",
    valueType: "boolean",
    defaultValue: true,
    proposalType: "editorial_rules",
  },
  {
    key: "min_article_length",
    label: "Longueur minimum d'un article",
    description: "Nombre minimum de caractères requis pour un article",
    category: "editorial",
    valueType: "number",
    defaultValue: 1000,
    proposalType: "editorial_rules",
    min: 100,
    max: 10000,
    step: 100,
    unit: "caractères",
  },
  {
    key: "max_article_length",
    label: "Longueur maximum d'un article",
    description: "Nombre maximum de caractères autorisés dans un article",
    category: "editorial",
    valueType: "number",
    defaultValue: 50000,
    proposalType: "editorial_rules",
    min: 1000,
    max: 200000,
    step: 1000,
    unit: "caractères",
  },
  {
    key: "max_tags_per_article",
    label: "Nombre maximum de tags par article",
    description: "Nombre maximum de tags qu'un utilisateur peut ajouter à un article",
    category: "editorial",
    valueType: "number",
    defaultValue: 10,
    proposalType: "editorial_rules",
    min: 1,
    max: 50,
    step: 1,
    unit: "tags",
  },

  // ============================================
  // PARAMÈTRES PRODUIT
  // ============================================
  {
    key: "min_votes_for_featured",
    label: "Nombre minimum de votes pour mise en vedette",
    description: "Nombre minimum de votes positifs requis pour qu'un article soit mis en vedette automatiquement",
    category: "product",
    valueType: "number",
    defaultValue: 10,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "votes",
  },
  {
    key: "notification_delay_hours",
    label: "Délai de notification (heures)",
    description: "Délai en heures avant d'envoyer une notification pour un événement",
    category: "product",
    valueType: "number",
    defaultValue: 24,
    proposalType: "product_evolution",
    min: 0,
    max: 168,
    step: 1,
    unit: "heures",
  },
  {
    key: "max_draft_articles_per_user",
    label: "Nombre maximum de brouillons par utilisateur",
    description: "Nombre maximum d'articles en brouillon qu'un utilisateur peut avoir simultanément",
    category: "product",
    valueType: "number",
    defaultValue: 10,
    proposalType: "product_evolution",
    min: 1,
    max: 50,
    step: 1,
    unit: "brouillons",
  },
  {
    key: "article_auto_archive_days",
    label: "Délai d'archivage automatique (jours)",
    description: "Nombre de jours d'inactivité avant qu'un article soit automatiquement archivé",
    category: "product",
    valueType: "number",
    defaultValue: 365,
    proposalType: "product_evolution",
    min: 30,
    max: 3650,
    step: 30,
    unit: "jours",
  },

  // ============================================
  // RÈGLES DE QUALITÉ D'ARTICLE
  // ============================================
  {
    key: "quality_score_scientific_bonus",
    label: "Bonus qualité pour articles scientifiques",
    description: "Points de bonus de qualité accordés aux articles scientifiques",
    category: "quality",
    valueType: "number",
    defaultValue: 20,
    proposalType: "editorial_rules",
    min: 0,
    max: 50,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_expert_bonus",
    label: "Bonus qualité pour articles d'experts",
    description: "Points de bonus de qualité accordés aux articles d'experts",
    category: "quality",
    valueType: "number",
    defaultValue: 15,
    proposalType: "editorial_rules",
    min: 0,
    max: 50,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_tutorial_bonus",
    label: "Bonus qualité pour tutoriels",
    description: "Points de bonus de qualité accordés aux tutoriels",
    category: "quality",
    valueType: "number",
    defaultValue: 10,
    proposalType: "editorial_rules",
    min: 0,
    max: 50,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_news_bonus",
    label: "Bonus qualité pour actualités",
    description: "Points de bonus de qualité accordés aux actualités",
    category: "quality",
    valueType: "number",
    defaultValue: 5,
    proposalType: "editorial_rules",
    min: 0,
    max: 50,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_opinion_bonus",
    label: "Bonus qualité pour articles d'opinion",
    description: "Points de bonus de qualité accordés aux articles d'opinion",
    category: "quality",
    valueType: "number",
    defaultValue: 3,
    proposalType: "editorial_rules",
    min: 0,
    max: 50,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_verification_ratio_weight",
    label: "Poids du ratio de vérification dans le score qualité",
    description: "Poids maximum (points) accordé au ratio de vérification des claims",
    category: "quality",
    valueType: "number",
    defaultValue: 40,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_expert_review_points",
    label: "Points par vérification experte",
    description: "Points de qualité accordés par vérification experte",
    category: "quality",
    valueType: "number",
    defaultValue: 5,
    proposalType: "editorial_rules",
    min: 0,
    max: 20,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_expert_review_max",
    label: "Maximum de points pour vérifications expertes",
    description: "Plafond de points de qualité pour les vérifications expertes",
    category: "quality",
    valueType: "number",
    defaultValue: 30,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "quality_score_community_weight",
    label: "Poids du score communautaire dans le score qualité",
    description: "Poids maximum (points) accordé au score de vérification communautaire",
    category: "quality",
    valueType: "number",
    defaultValue: 20,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "high_quality_article_threshold",
    label: "Seuil de qualité pour article de haute qualité",
    description: "Score de qualité minimum (0-100) pour considérer un article comme de haute qualité",
    category: "quality",
    valueType: "number",
    defaultValue: 70,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "high_quality_source_threshold",
    label: "Seuil de fiabilité pour source de haute qualité",
    description: "Score de fiabilité minimum (0-100) pour considérer une source comme de haute qualité",
    category: "quality",
    valueType: "number",
    defaultValue: 70,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "default_source_reliability_score",
    label: "Score de fiabilité par défaut d'une source",
    description: "Score de fiabilité initial (0-100) attribué à une nouvelle source",
    category: "quality",
    valueType: "number",
    defaultValue: 50,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },

  // ============================================
  // RÈGLES DE CRÉDIBILITÉ
  // ============================================
  {
    key: "credibility_publication_weight",
    label: "Poids des publications dans le score de crédibilité",
    description: "Poids maximum (points) accordé aux publications dans le calcul de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 30,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "credibility_sources_weight",
    label: "Poids des sources dans le score de crédibilité",
    description: "Poids maximum (points) accordé aux sources dans le calcul de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 20,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "credibility_votes_weight",
    label: "Poids des votes dans le score de crédibilité",
    description: "Poids maximum (points) accordé aux votes dans le calcul de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 20,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "credibility_corrections_weight",
    label: "Poids des corrections dans le score de crédibilité",
    description: "Poids maximum (points) accordé aux corrections dans le calcul de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 15,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "credibility_expertise_weight",
    label: "Poids de l'expertise dans le score de crédibilité",
    description: "Poids maximum (points) accordé à l'expertise dans le calcul de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 10,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "credibility_behavior_weight",
    label: "Poids des comportements positifs dans le score de crédibilité",
    description: "Poids maximum (points) accordé aux comportements positifs dans le calcul de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 5,
    proposalType: "editorial_rules",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "credibility_articles_per_points",
    label: "Nombre d'articles par point de crédibilité",
    description: "Nombre d'articles de haute qualité nécessaires pour 1 point de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 10,
    proposalType: "editorial_rules",
    min: 1,
    max: 100,
    step: 1,
    unit: "articles",
  },
  {
    key: "credibility_sources_per_points",
    label: "Nombre de sources par point de crédibilité",
    description: "Nombre de sources de haute qualité nécessaires pour 1 point de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 10,
    proposalType: "editorial_rules",
    min: 1,
    max: 100,
    step: 1,
    unit: "sources",
  },
  {
    key: "credibility_corrections_per_points",
    label: "Nombre de corrections par point de crédibilité",
    description: "Nombre de corrections approuvées nécessaires pour 1 point de crédibilité",
    category: "credibility",
    valueType: "number",
    defaultValue: 5,
    proposalType: "editorial_rules",
    min: 1,
    max: 50,
    step: 1,
    unit: "corrections",
  },
  {
    key: "credibility_expert_verification_points",
    label: "Points de crédibilité par vérification experte",
    description: "Points de crédibilité accordés par vérification experte",
    category: "credibility",
    valueType: "number",
    defaultValue: 2,
    proposalType: "editorial_rules",
    min: 0,
    max: 10,
    step: 0.5,
    unit: "points",
  },
  {
    key: "credibility_regular_verification_points",
    label: "Points de crédibilité par vérification régulière",
    description: "Points de crédibilité accordés par vérification non experte",
    category: "credibility",
    valueType: "number",
    defaultValue: 0.5,
    proposalType: "editorial_rules",
    min: 0,
    max: 5,
    step: 0.1,
    unit: "points",
  },
  {
    key: "credibility_expertise_domain_bonus",
    label: "Bonus de crédibilité par domaine d'expertise",
    description: "Points de crédibilité accordés par domaine d'expertise",
    category: "credibility",
    valueType: "number",
    defaultValue: 1,
    proposalType: "editorial_rules",
    min: 0,
    max: 10,
    step: 0.5,
    unit: "points",
  },
  {
    key: "credibility_mission_completed_points",
    label: "Points de crédibilité par mission complétée",
    description: "Points de crédibilité accordés lorsqu'une mission est complétée",
    category: "credibility",
    valueType: "number",
    defaultValue: 2,
    proposalType: "editorial_rules",
    min: 0,
    max: 10,
    step: 0.5,
    unit: "points",
  },

  // ============================================
  // PARAMÈTRES DE VOTE (GOUVERNANCE)
  // ============================================
  {
    key: "governance_default_quorum",
    label: "Quorum par défaut pour les votes de gouvernance",
    description: "Nombre minimum de votes requis par défaut pour valider une proposition",
    category: "governance",
    valueType: "number",
    defaultValue: 10,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "votes",
  },
  {
    key: "governance_default_majority",
    label: "Majorité par défaut pour les votes de gouvernance",
    description: "Pourcentage minimum de votes favorables requis par défaut",
    category: "governance",
    valueType: "number",
    defaultValue: 50,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "%",
  },
  {
    key: "governance_default_duration_days",
    label: "Durée par défaut des votes de gouvernance (jours)",
    description: "Durée par défaut en jours pour un vote de gouvernance",
    category: "governance",
    valueType: "number",
    defaultValue: 7,
    proposalType: "product_evolution",
    min: 1,
    max: 90,
    step: 1,
    unit: "jours",
  },
  {
    key: "governance_editorial_rules_quorum",
    label: "Quorum minimum pour règles éditoriales",
    description: "Quorum minimum requis pour les propositions de règles éditoriales",
    category: "governance",
    valueType: "number",
    defaultValue: 15,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "votes",
  },
  {
    key: "governance_editorial_rules_majority",
    label: "Majorité minimum pour règles éditoriales",
    description: "Majorité minimum requise pour les propositions de règles éditoriales",
    category: "governance",
    valueType: "number",
    defaultValue: 60,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "%",
  },
  {
    key: "governance_ethical_charter_quorum",
    label: "Quorum minimum pour charte éthique",
    description: "Quorum minimum requis pour les propositions de charte éthique",
    category: "governance",
    valueType: "number",
    defaultValue: 20,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "votes",
  },
  {
    key: "governance_ethical_charter_majority",
    label: "Majorité minimum pour charte éthique",
    description: "Majorité minimum requise pour les propositions de charte éthique",
    category: "governance",
    valueType: "number",
    defaultValue: 66,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "%",
  },
  {
    key: "governance_ethical_charter_extra_days",
    label: "Jours supplémentaires pour charte éthique",
    description: "Jours supplémentaires accordés pour les votes sur la charte éthique",
    category: "governance",
    valueType: "number",
    defaultValue: 3,
    proposalType: "product_evolution",
    min: 0,
    max: 30,
    step: 1,
    unit: "jours",
  },
  {
    key: "governance_expert_nomination_quorum",
    label: "Quorum minimum pour nomination d'expert",
    description: "Quorum minimum requis pour les propositions de nomination d'expert",
    category: "governance",
    valueType: "number",
    defaultValue: 12,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "votes",
  },
  {
    key: "governance_category_addition_quorum",
    label: "Quorum minimum pour ajout de catégorie",
    description: "Quorum minimum requis pour les propositions d'ajout de catégorie",
    category: "governance",
    valueType: "number",
    defaultValue: 10,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "votes",
  },
  {
    key: "governance_product_evolution_quorum",
    label: "Quorum minimum pour évolution produit",
    description: "Quorum minimum requis pour les propositions d'évolution produit",
    category: "governance",
    valueType: "number",
    defaultValue: 12,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "votes",
  },
  {
    key: "governance_product_evolution_majority",
    label: "Majorité minimum pour évolution produit",
    description: "Majorité minimum requise pour les propositions d'évolution produit",
    category: "governance",
    valueType: "number",
    defaultValue: 55,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "%",
  },

  // ============================================
  // LIMITES ET PAGINATION
  // ============================================
  {
    key: "default_list_limit",
    label: "Limite par défaut pour les listes",
    description: "Nombre d'éléments par défaut retournés dans les listes (pagination)",
    category: "product",
    valueType: "number",
    defaultValue: 20,
    proposalType: "product_evolution",
    min: 1,
    max: 1000,
    step: 1,
    unit: "éléments",
  },
  {
    key: "min_credibility_to_comment",
    label: "Crédibilité minimale pour commenter",
    description: "Points de crédibilité minimum requis pour pouvoir commenter des contenus",
    category: "product",
    valueType: "number",
    defaultValue: 10,
    proposalType: "product_evolution",
    min: 0,
    max: 1000,
    step: 1,
    unit: "points",
  },
  {
    key: "user_initial_level",
    label: "Niveau initial d'un utilisateur",
    description: "Niveau de départ pour un nouvel utilisateur",
    category: "product",
    valueType: "number",
    defaultValue: 1,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "niveau",
  },
  {
    key: "max_user_level",
    label: "Niveau maximum d'un utilisateur",
    description: "Niveau maximum qu'un utilisateur peut atteindre",
    category: "product",
    valueType: "number",
    defaultValue: 5,
    proposalType: "product_evolution",
    min: 1,
    max: 100,
    step: 1,
    unit: "niveau",
  },
  {
    key: "level_2_credibility_threshold",
    label: "Seuil de crédibilité pour niveau 2",
    description: "Score de crédibilité minimum requis pour atteindre le niveau 2",
    category: "product",
    valueType: "number",
    defaultValue: 20,
    proposalType: "product_evolution",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "level_3_credibility_threshold",
    label: "Seuil de crédibilité pour niveau 3",
    description: "Score de crédibilité minimum requis pour atteindre le niveau 3",
    category: "product",
    valueType: "number",
    defaultValue: 40,
    proposalType: "product_evolution",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "level_4_credibility_threshold",
    label: "Seuil de crédibilité pour niveau 4",
    description: "Score de crédibilité minimum requis pour atteindre le niveau 4",
    category: "product",
    valueType: "number",
    defaultValue: 60,
    proposalType: "product_evolution",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
  {
    key: "level_5_credibility_threshold",
    label: "Seuil de crédibilité pour niveau 5",
    description: "Score de crédibilité minimum requis pour atteindre le niveau 5",
    category: "product",
    valueType: "number",
    defaultValue: 80,
    proposalType: "product_evolution",
    min: 0,
    max: 100,
    step: 1,
    unit: "points",
  },
];

/**
 * Récupère une règle par défaut par sa clé
 */
export function getDefaultRule(key: string): DefaultRule | undefined {
  return DEFAULT_RULES.find((rule) => rule.key === key);
}

/**
 * Récupère toutes les règles par défaut pour un type de proposition
 */
export function getDefaultRulesForProposalType(
  proposalType: "editorial_rules" | "product_evolution" | "ethical_charter" | "other"
): DefaultRule[] {
  return DEFAULT_RULES.filter((rule) => rule.proposalType === proposalType);
}

